### ISSUE TITLE
Consider packaging tests in pypi source bundle

### ISSUE THREAD

**Issue by mildlyincompetent** [clbarnes/coordinates#8]
For distributions that use PyPi as a source of truth, packaging tests in the PyPi source bundle is a way to ensure the package can be tested if it is being built from the source bundle (this is of course not needed for the wheel distribution).

**Comment by clbarnes** [comment]
There's a spread of opinions, but the last time I read into it it looked like people were converging on tests outside of the source directory as the best practice generally. I prefer it because I've hit plenty of bugs relating to installation which are caught by tests outside the source directory (because they depend on the installation), but pass tests inside the source directory (because they can look up the local path).

I'm open to having my mind changed on this, though. How would you go about packaging the tests with the source bundle and not the wheel?

**Comment by mildlyincompetent** [comment]
I think your response makes sense; there is tooling that can do fancier packaging which I believe supports this, but it seems like far too much effort for the limited (possible) improvement.

When it comes to packaging coordinates I've found I can just switch to pulling the tagged version from github so this is now a non-issue for me.

Closing this for now as the approach of fetching from github works for my use case.
